site_name: 2020_5BI_Team4

nav:
    - 'Project Charter': 'project_charter.md'
    - 'Software Requirements Specification': 'software_requirements_specification.md'
    - 'Software Project Management Plan': 'software_project_management_plan.md'
   
    
theme:
    name: readthedocs

