site_name: '5BI Team 4 (2019/20)'
site_description: 'Documentation for GPI'
repo_url: https://github.com/SartoRiccardo/2020_5bi_team4_chat_protocol

nav:
    - December:
        - Project Charter: project_charter.md
        - Business Model Canvas: pdf/business_model_canvas.pdf
        - Software Requirements Specification: software_requirements_specification.md
        - Software Project Management Plan: software_project_management_plan.md
        - Project Model Canvas: pdf/project_model_canvas.pdf
    - April:
        - Release Plan: release_plan.md
        - Iteration Plan: iteration_plan.md
        - Project Success Criteria: project_success_criteria.md
        - Architecture and Design: architecture_and_design.md
        - Coding Standards: coding_standards.md
        - Test Plan: test_plan.md
        - Test Case Specification: test_case_specification.md
        - User Guide: user_guide.md
        - System Requirements: system_requirements.md
    
theme:
    name: readthedocs
    highlightjs: true
