site_name: '5BI Team 4 (2019/20)'
site_description: 'Documentation for GPI'
repo_url: 'https://github.com/SartoRiccardo/pcto-anagrafe'

nav:
    - 'Project Charter': 'project_charter.md'
    - 'Business Model Canvas': 'pdf/business_model_canvas.pdf'
    - 'Software Requirements Specification': 'software_requirements_specification.md'
    - 'Software Project Management Plan': 'software_project_management_plan.md'
    - 'Project Model Canvas': 'pdf/project_model_canvas.pdf'
    
theme:
    name: readthedocs

